-- MySQL Script generated by MySQL Workbench
-- 02/05/23 13:16:25
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema farmlestari_akuntansi_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema farmlestari_akuntansi_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `farmlestari_akuntansi_db` DEFAULT CHARACTER SET utf8 ;
USE `farmlestari_akuntansi_db` ;

-- -----------------------------------------------------
-- Table `farmlestari_akuntansi_db`.`periode`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmlestari_akuntansi_db`.`periode` (
  `id` INT NOT NULL,
  `tanggal_awal` DATE NULL,
  `tanggal_akhir` DATE NULL,
  `status` TINYINT(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmlestari_akuntansi_db`.`akun`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmlestari_akuntansi_db`.`akun` (
  `no_akun` VARCHAR(15) NOT NULL,
  `nama` VARCHAR(45) NULL,
  `jenis_akun` ENUM('aset', 'kewajiban', 'ekuitas', 'pendapatan', 'biaya') NULL,
  `saldo_awal` INT NULL,
  PRIMARY KEY (`no_akun`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmlestari_akuntansi_db`.`transaksi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmlestari_akuntansi_db`.`transaksi` (
  `id` INT NOT NULL,
  `keterangan` VARCHAR(200) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmlestari_akuntansi_db`.`jurnal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmlestari_akuntansi_db`.`jurnal` (
  `id` INT NOT NULL,
  `jenis` ENUM('umum', 'penyesuaian', 'penutup') NULL,
  `tanggal_transaksi` DATE NULL,
  `no_bukti` VARCHAR(45) NULL,
  `transaksi_id` INT NOT NULL,
  `periode_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_jurnal_transaksi1_idx` (`transaksi_id` ASC),
  INDEX `fk_jurnal_periode1_idx` (`periode_id` ASC),
  CONSTRAINT `fk_jurnal_transaksi1`
    FOREIGN KEY (`transaksi_id`)
    REFERENCES `farmlestari_akuntansi_db`.`transaksi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jurnal_periode1`
    FOREIGN KEY (`periode_id`)
    REFERENCES `farmlestari_akuntansi_db`.`periode` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmlestari_akuntansi_db`.`jurnal_has_akun`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmlestari_akuntansi_db`.`jurnal_has_akun` (
  `jurnal_id` INT NOT NULL,
  `akun_no_akun` VARCHAR(15) NOT NULL,
  `no_urut` INT NULL,
  `nominal_debit` INT NULL,
  `nominal_kredit` INT NULL,
  PRIMARY KEY (`jurnal_id`, `akun_no_akun`),
  INDEX `fk_jurnal_has_akun_akun1_idx` (`akun_no_akun` ASC),
  INDEX `fk_jurnal_has_akun_jurnal1_idx` (`jurnal_id` ASC),
  CONSTRAINT `fk_jurnal_has_akun_jurnal1`
    FOREIGN KEY (`jurnal_id`)
    REFERENCES `farmlestari_akuntansi_db`.`jurnal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jurnal_has_akun_akun1`
    FOREIGN KEY (`akun_no_akun`)
    REFERENCES `farmlestari_akuntansi_db`.`akun` (`no_akun`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
